(*** hide ***)
// This block of code is omitted in the generated HTML documentation. Use 
// it to define helpers that you do not want to show in the documentation.
#I "../../bin/FSharpGephiStreamer/net47"

(**
Streaming a graph to gephi 
==========================
[Gephi](https://gephi.org/) enables the visualization and exploration of all kinds of graphs and networks.
The library FSharpGephiStreamer provides functions suitable for use from F# scripting to stream graph data 
to [gephi](https://gephi.org/).
*)
#r "FSharpGephiStreamer.dll"
open FSharpGephiStreamer
(**
<img src="./img/OboNetworkMeta.png" usemap="#NetworkMap">
<map name="NetworkMap">
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <area target="" alt="Binding"                   title="Binding"                 href="#Binding"                 coords="127,192,115" shape="circle">
    <area target="" alt="Transferases"              title="Transferases"            href="#Transferases"            coords="276,81,343,31,433,3,488,28,461,116,374,171,298,179,264,147,261,112" shape="poly">
    <area target="" alt="Regulation"                title="Regulation"              href="#Regulation"              coords="469,823,139" shape="circle">
    <area target="" alt="Protein-Complex"           title="Protein-Complex"         href="#Protein-Complex"         coords="468,207,62" shape="circle">
    <area target="" alt="Metabolic-Processes"       title="Metabolic-Processes"     href="#Metabolic-Processes"     coords="125,608,88,628,44,669,41,740,89,795,180,821,248,817,308,778,336,727,328,659,283,623,219,602,170,601" shape="poly">
    <area target="" alt="Oxireductases"             title="Oxireductases"           href="#Oxireductases"           coords="571,267,532,262,498,280,492,299,507,350,540,423,607,498,676,558,749,594,782,598,800,584,806,558,793,505,733,404,656,323" shape="poly">
    <area target="" alt="Intracellular-Transport"   title="Intracellular-Transport" href="#Intracellular-Transport" coords="482,527,533,485,576,486,596,503,602,524,606,553,596,594,565,632,533,651,490,655,464,632,459,584,469,555" shape="poly">
    <area target="" alt="Reproduction"              title="Reproduction"            href="#Reproduction"            coords="600,610,640,587,684,584,719,610,724,643,709,695,675,717,621,732,576,709,569,676,574,643" shape="poly">
    <area target="" alt="Transmembrane-Transport"   title="Transmembrane-Transport" href="#Transmembrane-Transport" coords="622,131,79" shape="circle">
</map>

##Binding
##Transferases
##Regulation
##Protein-Complex
##Metabolic-Processes
##Oxireductases
##Intracellular-Transport
##Reproduction
##Transmembrane-Transport

*)