// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpGephiStreamer")>]
[<assembly: AssemblyProductAttribute("FSharpGephiStreamer")>]
[<assembly: AssemblyDescriptionAttribute("F# functions for streaming any kind of graph/network data to the network visualization tool gephi")>]
[<assembly: AssemblyVersionAttribute("1.1.4")>]
[<assembly: AssemblyFileVersionAttribute("1.1.4")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpGephiStreamer"
    let [<Literal>] AssemblyProduct = "FSharpGephiStreamer"
    let [<Literal>] AssemblyDescription = "F# functions for streaming any kind of graph/network data to the network visualization tool gephi"
    let [<Literal>] AssemblyVersion = "1.1.4"
    let [<Literal>] AssemblyFileVersion = "1.1.4"
    let [<Literal>] AssemblyConfiguration = "Release"
