// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpGephiStreamer")>]
[<assembly: AssemblyProductAttribute("FSharpGephiStreamer")>]
[<assembly: AssemblyDescriptionAttribute("FSharp functions for streaming graph data to gephi a graph visualization tool")>]
[<assembly: AssemblyVersionAttribute("1.1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpGephiStreamer"
    let [<Literal>] AssemblyProduct = "FSharpGephiStreamer"
    let [<Literal>] AssemblyDescription = "FSharp functions for streaming graph data to gephi a graph visualization tool"
    let [<Literal>] AssemblyVersion = "1.1.0"
    let [<Literal>] AssemblyFileVersion = "1.1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
